baseURL = "https://us.shoogle.net/south-carolina"
languageCode = "en-US"
title = "South Carolina"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "south-carolina"
